# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b9ce02b52f3165c38553d29d3f343039192d9e61ed63b2e04010ef1d3e52d1076141a22a923d5dc23918950b8e267c18c1a2fcd38b4737d90748e0eb9ff2765

test:
  secret_key_base: cba63bc366b0ff58126a1c3b9fe9de1797fe6c3ce938209a51a81e7594082afe4ea3c578143f090f5ac19258bf35162178d9be4ea32c529c01799426370230a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
